from sqlalchemy import inspect, text

from app.db.base import engine


def _database_sql(statement: str) -> str:
    if engine.dialect.name != "postgresql":
        return statement

    replacements = {
        "id INTEGER PRIMARY KEY": "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "DATETIME": "TIMESTAMP WITH TIME ZONE",
        "BOOLEAN NOT NULL DEFAULT FALSE": "BOOLEAN NOT NULL DEFAULT false",
        "BOOLEAN NOT NULL DEFAULT 1": "BOOLEAN NOT NULL DEFAULT true",
    }
    for old, new in replacements.items():
        statement = statement.replace(old, new)
    return statement


def _execute_statements(statements: list[str]) -> None:
    if not statements:
        return

    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(_database_sql(stmt)))


def ensure_runtime_schema():
    inspector = inspect(engine)

    if inspector.has_table("events"):
        event_columns = {col["name"] for col in inspector.get_columns("events")}
        event_statements = []
        if "snapshot_path" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN snapshot_path VARCHAR")
        if "started_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN started_at DATETIME")
        if "ended_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN ended_at DATETIME")
        if "bbox_json" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN bbox_json TEXT")
        if "detector_score" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN detector_score FLOAT")
        if "severity" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN severity VARCHAR")
        if "status" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN status VARCHAR")
        if "event_score" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN event_score FLOAT")
        if "alarm_eligible" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN alarm_eligible BOOLEAN")
        if "lifecycle_action" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN lifecycle_action VARCHAR")
        if "alarm_category" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN alarm_category VARCHAR")
        if "clip_path" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_path VARCHAR")
        if "clip_remote_item_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_remote_item_id VARCHAR")
        if "clip_remote_web_url" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_remote_web_url VARCHAR")
        if "clip_remote_status" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_remote_status VARCHAR")
        if "clip_remote_uploaded_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_remote_uploaded_at DATETIME")
        if "clip_local_deleted_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN clip_local_deleted_at DATETIME")
        if "snapshot_remote_item_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN snapshot_remote_item_id VARCHAR")
        if "snapshot_remote_web_url" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN snapshot_remote_web_url VARCHAR")
        if "snapshot_remote_status" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN snapshot_remote_status VARCHAR")
        if "snapshot_remote_uploaded_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN snapshot_remote_uploaded_at DATETIME")
        if "event_remote_item_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN event_remote_item_id VARCHAR")
        if "event_remote_web_url" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN event_remote_web_url VARCHAR")
        if "event_remote_status" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN event_remote_status VARCHAR")
        if "event_remote_uploaded_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN event_remote_uploaded_at DATETIME")
        if "active_profile_snapshot" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN active_profile_snapshot TEXT")
        if "threshold_snapshot" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN threshold_snapshot TEXT")
        if "scene_profile" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN scene_profile VARCHAR")
        if "camera_family" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN camera_family VARCHAR")
        if "nuisance_profile_snapshot" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN nuisance_profile_snapshot TEXT")
        if "roi_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN roi_id VARCHAR")
        if "zone_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN zone_id VARCHAR")
        if "rule_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN rule_id VARCHAR")
        if "correlation_key" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN correlation_key VARCHAR")
        if "related_event_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN related_event_id INTEGER")
        if "resolved_by_event_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN resolved_by_event_id INTEGER")
        if "resolved_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN resolved_at DATETIME")
        if "is_alarm_active" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN is_alarm_active BOOLEAN")
        if "operator_note" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN operator_note TEXT")
        if "acknowledged_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN acknowledged_at DATETIME")
        if "closed_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN closed_at DATETIME")
        if "assigned_user_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN assigned_user_id INTEGER")
        if "assigned_username" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN assigned_username VARCHAR")
        if "sla_due_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN sla_due_at DATETIME")
        if "escalated_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN escalated_at DATETIME")
        if "resolution_code" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN resolution_code VARCHAR")
        if "incident_team" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN incident_team VARCHAR")
        if "incident_priority" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN incident_priority VARCHAR")
        if "incident_checklist" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN incident_checklist TEXT")
        if "incident_origin" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN incident_origin VARCHAR")
        if "incident_parent_id" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN incident_parent_id INTEGER")
        if "ai_validation_label" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN ai_validation_label VARCHAR")
        if "ai_validation_reason" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN ai_validation_reason VARCHAR")
        if "ai_validation_at" not in event_columns:
            event_statements.append("ALTER TABLE events ADD COLUMN ai_validation_at DATETIME")
        _execute_statements(event_statements)

    if not inspector.has_table("lockdown_deliveries"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE lockdown_deliveries (
                        id INTEGER PRIMARY KEY,
                        event_id INTEGER NOT NULL REFERENCES events(id),
                        camera_id INTEGER NOT NULL,
                        event_type VARCHAR NOT NULL,
                        target_url VARCHAR NOT NULL,
                        request_body TEXT,
                        request_timestamp INTEGER,
                        request_signature VARCHAR,
                        status VARCHAR NOT NULL,
                        attempt_count INTEGER NOT NULL DEFAULT 0,
                        http_status INTEGER,
                        response_body TEXT,
                        error_message TEXT,
                        last_attempt_at DATETIME,
                        sent_at DATETIME,
                        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                ))
            )
    elif inspector.has_table("lockdown_deliveries"):
        delivery_columns = {col["name"] for col in inspector.get_columns("lockdown_deliveries")}
        delivery_statements = []
        if "event_id" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN event_id INTEGER")
        if "camera_id" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN camera_id INTEGER")
        if "event_type" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN event_type VARCHAR")
        if "target_url" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN target_url VARCHAR")
        if "request_body" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN request_body TEXT")
        if "request_timestamp" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN request_timestamp INTEGER")
        if "request_signature" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN request_signature VARCHAR")
        if "status" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN status VARCHAR")
        if "attempt_count" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN attempt_count INTEGER DEFAULT 0")
        if "http_status" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN http_status INTEGER")
        if "response_body" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN response_body TEXT")
        if "error_message" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN error_message TEXT")
        if "last_attempt_at" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN last_attempt_at DATETIME")
        if "sent_at" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN sent_at DATETIME")
        if "created_at" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN created_at DATETIME")
        if "updated_at" not in delivery_columns:
            delivery_statements.append("ALTER TABLE lockdown_deliveries ADD COLUMN updated_at DATETIME")
        _execute_statements(delivery_statements)

    if inspector.has_table("cameras"):
        camera_columns = {col["name"] for col in inspector.get_columns("cameras")}
        camera_statements = []
        if "roi_name" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN roi_name VARCHAR")
        if "roi_polygon_json" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN roi_polygon_json TEXT")
        if "line_start_x" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN line_start_x FLOAT")
        if "line_start_y" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN line_start_y FLOAT")
        if "line_end_x" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN line_end_x FLOAT")
        if "line_end_y" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN line_end_y FLOAT")
        if "line_direction" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN line_direction VARCHAR")
        if "analytics_coordinate_space" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN analytics_coordinate_space VARCHAR")
        if "human_event_modes_json" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN human_event_modes_json TEXT")
        if "human_loitering_seconds" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN human_loitering_seconds FLOAT")
        if "human_detection_sensitivity" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN human_detection_sensitivity VARCHAR")
        if "analytics_profile_json" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN analytics_profile_json TEXT")
        if "learning_mode" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN learning_mode VARCHAR")
        if "auto_tuning_enabled" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN auto_tuning_enabled BOOLEAN")
        if "critical_lock" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN critical_lock BOOLEAN")
        if "max_daily_auto_changes" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN max_daily_auto_changes INTEGER")
        if "min_reviewed_events_for_suggestion" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN min_reviewed_events_for_suggestion INTEGER")
        if "min_reviewed_events_for_auto_tuning" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN min_reviewed_events_for_auto_tuning INTEGER")
        if "rollback_window_hours" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN rollback_window_hours INTEGER")
        if "site_name" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN site_name VARCHAR")
        if "group_name" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN group_name VARCHAR")
        if "manufacturer" not in camera_columns:
            camera_statements.append(
                "ALTER TABLE cameras ADD COLUMN manufacturer VARCHAR(120) NOT NULL DEFAULT 'Nao informada'"
            )
        if "model" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN model VARCHAR(120)")
        if "camera_priority" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN camera_priority VARCHAR")
        if "auto_start_enabled" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN auto_start_enabled BOOLEAN")
        if "alarm_sound_enabled" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN alarm_sound_enabled BOOLEAN")
        if "alarm_popup_enabled" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN alarm_popup_enabled BOOLEAN")
        if "motion_idle_interval" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_idle_interval FLOAT")
        if "motion_active_interval" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_active_interval FLOAT")
        if "motion_hold_seconds" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_hold_seconds FLOAT")
        if "motion_detection_hold_seconds" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_detection_hold_seconds FLOAT")
        if "motion_min_motion_frames" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_min_motion_frames INTEGER")
        if "motion_downscale_width" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_downscale_width INTEGER")
        if "motion_min_contour_area" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_min_contour_area INTEGER")
        if "motion_ratio_threshold" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_ratio_threshold FLOAT")
        if "motion_global_change_ratio_limit" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_global_change_ratio_limit FLOAT")
        if "motion_background_alpha" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_background_alpha FLOAT")
        if "motion_warmup_frames" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN motion_warmup_frames INTEGER")
        if "is_deleted" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
        if "deleted_at" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN deleted_at DATETIME")
        if "source_type" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_type VARCHAR")
        if "source_parent_id" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_parent_id INTEGER")
        if "source_channel" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_channel INTEGER")
        if "source_stream_kind" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_stream_kind VARCHAR")
        if "source_brand" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_brand VARCHAR")
        if "source_provider" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_provider VARCHAR")
        _execute_statements(camera_statements)

    if not inspector.has_table("camera_ptz_profiles"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE camera_ptz_profiles (
                        id INTEGER PRIMARY KEY,
                        camera_id INTEGER NOT NULL UNIQUE REFERENCES cameras(id),
                        status VARCHAR(32) NOT NULL DEFAULT 'unknown',
                        detected_brand VARCHAR(32),
                        selected_backend VARCHAR(32),
                        fallback_backend VARCHAR(32),
                        control_port INTEGER,
                        channel INTEGER,
                        profile_token VARCHAR(255),
                        supports_pan_tilt BOOLEAN NOT NULL DEFAULT FALSE,
                        supports_zoom BOOLEAN NOT NULL DEFAULT FALSE,
                        supports_presets BOOLEAN NOT NULL DEFAULT FALSE,
                        continuous_move BOOLEAN NOT NULL DEFAULT FALSE,
                        configuration_fingerprint VARCHAR(64),
                        failure_count INTEGER NOT NULL DEFAULT 0,
                        last_error_category VARCHAR(64),
                        last_error TEXT,
                        diagnostics_json TEXT,
                        last_verified_at DATETIME,
                        last_success_at DATETIME,
                        next_retry_at DATETIME,
                        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                ))
            )
            conn.execute(text("CREATE INDEX ix_camera_ptz_profiles_camera_id ON camera_ptz_profiles(camera_id)"))

    ptz_profile_columns = {col["name"] for col in inspect(engine).get_columns("camera_ptz_profiles")}
    if "diagnostics_json" not in ptz_profile_columns:
        _execute_statements(["ALTER TABLE camera_ptz_profiles ADD COLUMN diagnostics_json TEXT"])

    if not inspector.has_table("event_feedback"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE event_feedback (
                        id INTEGER PRIMARY KEY,
                        event_id INTEGER NOT NULL REFERENCES events(id),
                        camera_id INTEGER NOT NULL REFERENCES cameras(id),
                        label VARCHAR NOT NULL,
                        probable_cause VARCHAR,
                        operator_note TEXT,
                        reviewed_by VARCHAR,
                        reviewed_at DATETIME DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                ))
            )
    if not inspector.has_table("tuning_suggestions"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE tuning_suggestions (
                        id INTEGER PRIMARY KEY,
                        camera_id INTEGER NOT NULL REFERENCES cameras(id),
                        scope_type VARCHAR NOT NULL,
                        scope_id VARCHAR NOT NULL,
                        suggestion_type VARCHAR NOT NULL,
                        parameter_name VARCHAR NOT NULL,
                        old_value TEXT,
                        suggested_value TEXT,
                        reason_summary TEXT,
                        evidence_count INTEGER NOT NULL DEFAULT 0,
                        confidence_score FLOAT NOT NULL DEFAULT 0,
                        status VARCHAR NOT NULL DEFAULT 'pending',
                        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                        applied_at DATETIME
                    )
                    """
                ))
            )
    if not inspector.has_table("config_version_history"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE config_version_history (
                        id INTEGER PRIMARY KEY,
                        camera_id INTEGER NOT NULL REFERENCES cameras(id),
                        config_before TEXT NOT NULL,
                        config_after TEXT NOT NULL,
                        change_source VARCHAR NOT NULL,
                        reason TEXT,
                        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                        rollback_available BOOLEAN NOT NULL DEFAULT 1
                    )
                    """
                ))
            )
    
    if inspector.has_table("users"):
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        user_statements = []
        if "login_attempts" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN login_attempts INTEGER NOT NULL DEFAULT 0")
        if "lockout_until" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN lockout_until DATETIME")
        if "must_change_password" not in user_columns:
            user_statements.append(
                "ALTER TABLE users ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE"
            )
        if "max_active_sessions" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN max_active_sessions INTEGER")
        _execute_statements(user_statements)

    if not inspector.has_table("audit_logs"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE audit_logs (
                        id INTEGER PRIMARY KEY,
                        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                        user_id INTEGER,
                        username VARCHAR,
                        action VARCHAR NOT NULL,
                        details TEXT,
                        ip_address VARCHAR
                    )
                    """
                ))
            )

    for table_name, columns in {
        "view_presets": {
            "owner_user_id": "INTEGER",
            "view_config_json": "TEXT",
            "is_shared": "BOOLEAN NOT NULL DEFAULT FALSE",
        },
        "temporal_sequences": {
            "owner_user_id": "INTEGER",
            "is_shared": "BOOLEAN NOT NULL DEFAULT FALSE",
        },
    }.items():
        if inspector.has_table(table_name):
            existing_columns = {col["name"] for col in inspector.get_columns(table_name)}
            _execute_statements([
                f"ALTER TABLE {table_name} ADD COLUMN {column_name} {definition}"
                for column_name, definition in columns.items()
                if column_name not in existing_columns
            ])

    # Indices compostos para as consultas mais comuns de eventos (lista por
    # camera, fila por status, retencao por data). CREATE INDEX IF NOT EXISTS e
    # idempotente, entao roda com seguranca em todo startup.
    if inspector.has_table("events"):
        index_statements = [
            "CREATE INDEX IF NOT EXISTS idx_events_camera_created ON events (camera_id, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_events_status_created ON events (status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_events_created ON events (created_at)",
        ]
        _execute_statements(index_statements)
