from sqlalchemy import inspect, text

from app.db.base import engine


def _database_sql(statement: str) -> str:
    if engine.dialect.name != "postgresql":
        return statement

    replacements = {
        "id INTEGER PRIMARY KEY": "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "DATETIME": "TIMESTAMP WITH TIME ZONE",
        "BOOLEAN NOT NULL DEFAULT FALSE": "BOOLEAN NOT NULL DEFAULT false",
        "BOOLEAN NOT NULL DEFAULT 1": "BOOLEAN NOT NULL DEFAULT true",
    }
    for old, new in replacements.items():
        statement = statement.replace(old, new)
    return statement


def _execute_statements(statements: list[str]) -> None:
    if not statements:
        return

    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(_database_sql(stmt)))


def ensure_runtime_schema():
    """Garante a migracao e presenca de tabelas e colunas do VMSun."""
    inspector = inspect(engine)

    if inspector.has_table("cameras"):
        camera_columns = {col["name"] for col in inspector.get_columns("cameras")}
        camera_statements = []
        if "customer_id" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN customer_id INTEGER")
        if "site_id" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN site_id INTEGER")
        if "nvr_id" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN nvr_id INTEGER")
        if "channel_number" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN channel_number INTEGER")
        if "sub_rtsp_url" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN sub_rtsp_url TEXT")
        if "manufacturer" not in camera_columns:
            camera_statements.append(
                "ALTER TABLE cameras ADD COLUMN manufacturer VARCHAR(120) NOT NULL DEFAULT 'Nao informada'"
            )
        if "model" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN model VARCHAR(120)")
        if "camera_priority" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN camera_priority VARCHAR")
        if "auto_start_enabled" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN auto_start_enabled BOOLEAN")
        if "is_deleted" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
        if "deleted_at" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN deleted_at DATETIME")
        if "source_type" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_type VARCHAR")
        if "source_parent_id" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_parent_id INTEGER")
        if "source_channel" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_channel INTEGER")
        if "source_stream_kind" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_stream_kind VARCHAR")
        if "source_brand" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_brand VARCHAR")
        if "source_provider" not in camera_columns:
            camera_statements.append("ALTER TABLE cameras ADD COLUMN source_provider VARCHAR")
        _execute_statements(camera_statements)

    if inspector.has_table("users"):
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        user_statements = []
        if "login_attempts" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN login_attempts INTEGER NOT NULL DEFAULT 0")
        if "lockout_until" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN lockout_until DATETIME")
        if "must_change_password" not in user_columns:
            user_statements.append(
                "ALTER TABLE users ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE"
            )
        if "max_active_sessions" not in user_columns:
            user_statements.append("ALTER TABLE users ADD COLUMN max_active_sessions INTEGER")
        _execute_statements(user_statements)

    if not inspector.has_table("audit_logs"):
        with engine.begin() as conn:
            conn.execute(
                text(_database_sql(
                    """
                    CREATE TABLE audit_logs (
                        id INTEGER PRIMARY KEY,
                        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                        user_id INTEGER,
                        username VARCHAR,
                        action VARCHAR NOT NULL,
                        details TEXT,
                        ip_address VARCHAR
                    )
                    """
                ))
            )
